version: '3.8'

services:
  puppeteer-server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  fastapi:
    build: ./fastapi
    ports:
      - "9595:8000"
    depends_on:
      - puppeteer-server
